-- =========================
-- AUTO_COLL（主表）
-- =========================
CREATE TABLE AUTO_COLL (
    PKID        VARCHAR2(200 CHAR)  NOT NULL,
    TRACEID     VARCHAR2(200 CHAR)  DEFAULT ' ' NOT NULL,
    COLLREQ     CLOB,
    COLLRES     CLOB,
    TXNCODE     VARCHAR2(100 CHAR),
    COLLTIME    VARCHAR2(60 CHAR),
    STATUS      VARCHAR2(1 CHAR),
    COLLHEADER  VARCHAR2(4000 CHAR),
    METHOD      VARCHAR2(500 CHAR),
    SERVICENAME VARCHAR2(500 CHAR),
    CONSTRAINT PK_AUTO_COLL PRIMARY KEY (PKID)
);

CREATE INDEX IDX_AUTO_COLL_MIX
    ON AUTO_COLL (COLLTIME, PKID, TRACEID);

CREATE INDEX IDX_AUTO_COLL_TRACEID
    ON AUTO_COLL (TRACEID);

COMMENT ON TABLE AUTO_COLL IS '流量采集表';
COMMENT ON COLUMN AUTO_COLL.PKID IS '唯一主键编号';
COMMENT ON COLUMN AUTO_COLL.TRACEID IS '全局流水';
COMMENT ON COLUMN AUTO_COLL.COLLREQ IS '采集请求报文';
COMMENT ON COLUMN AUTO_COLL.COLLRES IS '采集返回报文';
COMMENT ON COLUMN AUTO_COLL.TXNCODE IS '接口码';
COMMENT ON COLUMN AUTO_COLL.COLLTIME IS '采集时间';
COMMENT ON COLUMN AUTO_COLL.STATUS IS '回放状态';
COMMENT ON COLUMN AUTO_COLL.COLLHEADER IS '请求报文头';
COMMENT ON COLUMN AUTO_COLL.METHOD IS '接口方法';
COMMENT ON COLUMN AUTO_COLL.SERVICENAME IS '微服务名称';


-- =========================
-- AUTO_COLL_FAIL（失败表）
-- =========================
CREATE TABLE AUTO_COLL_FAIL (
    PKID        VARCHAR2(200 CHAR)  NOT NULL,
    TRACEID     VARCHAR2(200 CHAR)  DEFAULT ' ' NOT NULL,
    COLLREQ     CLOB,
    COLLRES     CLOB,
    TXNCODE     VARCHAR2(100 CHAR),
    COLLTIME    VARCHAR2(60 CHAR),
    STATUS      VARCHAR2(1 CHAR),
    COLLHEADER  VARCHAR2(4000 CHAR),
    METHOD      VARCHAR2(500 CHAR),
    SERVICENAME VARCHAR2(500 CHAR),
    CONSTRAINT PK_AUTO_COLL_FAIL PRIMARY KEY (PKID)
);

CREATE INDEX IDX_AUTO_COLL_FAIL_MIX
    ON AUTO_COLL_FAIL (COLLTIME, PKID, TRACEID);

CREATE INDEX IDX_AUTO_COLL_FAIL_TRACEID
    ON AUTO_COLL_FAIL (TRACEID);

COMMENT ON TABLE AUTO_COLL_FAIL IS '流量采集失败表';
COMMENT ON COLUMN AUTO_COLL_FAIL.PKID IS '唯一主键编号';
COMMENT ON COLUMN AUTO_COLL_FAIL.TRACEID IS '全局流水';
COMMENT ON COLUMN AUTO_COLL_FAIL.COLLREQ IS '采集请求报文';
COMMENT ON COLUMN AUTO_COLL_FAIL.COLLRES IS '采集返回报文';
COMMENT ON COLUMN AUTO_COLL_FAIL.TXNCODE IS '接口码';
COMMENT ON COLUMN AUTO_COLL_FAIL.COLLTIME IS '采集时间';
COMMENT ON COLUMN AUTO_COLL_FAIL.STATUS IS '回放状态';
COMMENT ON COLUMN AUTO_COLL_FAIL.COLLHEADER IS '请求报文头';
COMMENT ON COLUMN AUTO_COLL_FAIL.METHOD IS '接口方法';
COMMENT ON COLUMN AUTO_COLL_FAIL.SERVICENAME IS '微服务名称';